# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    body_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
            html: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    serializer: { serialize_null: true }
#    service:
#        templating: templating
