homepage:
  path: /
  methods: [GET]
  controller: App\Controller\Frontend\DefaultController::index

api:
    prefix: '_api'
    type: 'rest'
    host: 'weak'
    name_prefix: 'api.'
    resource: 'routes/api.yaml'
