app.home:
  path: /
  methods: [GET]
  controller: App\Controller\Frontend\DefaultController::index

api:
    prefix: '_api'
    type: 'rest'
    host: 'weak'
    name_prefix: 'api.'
    resource: 'routes/api.yaml'
security:
    name_prefix: 'app.'
    resource: 'routes/security.yaml'
callback:
    prefix: 'callback'
    type: 'rest'
    name_prefix: 'callback.'
    resource: 'routes/callbacks.yaml'